language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: CQNpUEvbSTaJpeUCpl3JYXfHvk4o7IUjFbHUnbKwgJBiZbKEodP5Ws3qJYRwPZQtSvcMyoAjBzHcTmhVRw7BCn1n4vs2qGzNJO0iAp/fmZbL6uowNwyx6wTF3s66F1eg9UscFpDN77vTxpAKN6nF4aMaJXomDr9AEypg5LhqmCDDmk54xmhOcw+D31CGTmrRTRJCz8cku42+Gc1tEhWKU6GmzPL/pDFlaQV58mB/Dpj5UJHdsR8kHGk+5MkZ39Gye6DRhn7xgbwksU2kNi4lJtok/nVdNdafqEF2vSsBUu57Wx/fX4HedYI2HFVrebduKNT4jfLle3235250glgkQ2DPYqI7iugi23EMJaGAOYGP3HifFRsg1JkAnKgELjRLNwrbMn9juAqoLrhwhts6BFWaYN7E+Ri2ofmqN5KXGtpKgSNEGlzrHjFc6YifONGNhe9168E4UauVYUGIdp/2XWkVPUxj/fX7XOoKD56m8nReQsmIXhG3UDrawhnaC1GE6YV/cXWnLexI2MMA8mXKG62PHF57pCgMYBhE1B7GXzKkx28gMpD3UWwEnhgyLDTxw+3Xu0ljXdpVbzg2Fx9b8SJPwX81+khhBWQ8GSRJjpHPmD30/bBAfrtCEKi8cXSsA6dfhC+VFjy95zHEJL3Qg2q9HXzd4Ow6o9bw7DddnwM=
  - secure: r2bjCq/zJxK2bVXXUTSVbDyLJyRLRJ6lvAXOZ+OzJc03Rnpp3qgi/L2HW7heKRYF7qp4uQVCl2JFiEl2Ky3WVg6FDTNCL42DXlp+SuSLpc215+dyHFQl4BLjX02xahuZubjdh3zNboRBfoj7Bt0mzZXiQ49CeBAL0b/JPgRFTNQAnoVZRd9oEykBpX1uXHAdcKE2AS+S/0tIEBjxSVUe2Q8hHc6OW7oLV5st+gR4S+YFRWioJ5gFWQBYnfSvFVWwOcXWfGs58xWXAwFb61kh4wZVwfwWhtpqKWyXhbj4E6xYKNlvAztqsiHpMo/FuobFPmdyjR5+anIzQAlCn4DdBPxPB6ZKlYb8E2i7pOhMFAeuifbek9tfHax8rdlZHC1JJW0DxqIro9LOIw4HRCqJDSjcj6suMOwp7sXdrXuAVjQcTTEQ4e7g50jeUCQW+k79rq8KX5HsfUPRRxooV1nZikwHn5oythPXUSiRI1yArPT/EdFyjpkiXcvePRvvQCfdQpnG2SrB2xeZa0MJpgDH6IFbdvN+VjXEf6ZSxj+HVWZ8YolK+bw4Rd//TPE2tFPw6FyPnAe0LgQIHkXv4HGwDRvRkf9NhmPPCxrmZ7N2phlme8AZhBY+3zRErK4cIDh/OqxgPhysDoTbYU4AXEMJS9zj7CjzI58yJ93zWmyChNE=
