language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: Qh3rwVllK+DZa9xgsaZsvwTz0yi6PuL4+VoxrUycOGFH8xzab5cVG8EsfgDCp6C/VWhwsPGnM8+XKKDFW7zFuIEG0QgoDex5jVO9r2UOq9kYDPZ7kSo21EpgQWWaGur4odIg+b/I6f5ZUdxi8U7Oenau3FP3UOPQSu/Jooq8CUayrqdxlEceSWqOhD3Q6KJxj5eDeSAuaaxecjcHg9h4bQ0dMjezUGFia1VhFfdRI39zQM2sNZ5NdhZpJ8sFzIjOzT/S1I/ZHSkyoIRrZzJbB3ixbmbeiQBxbIFLIbMs1di1o0nsk57QePwUge7p+1pyBQEYY/5ZFM15ShZFCRTDAyzrRyXl/aw/KAuYy94/0qQkydomdzaIwwKwcmWSj9+kPPz3D8QjlyCenoUPBsZUETbjaxn4KBZ416DLNIVVbU7g6YcCC3eeoPFOmmPp+46S98//Aoiuo7+yKwUBG2da5hnbc0MUXxQ1JaQcJGhcmRZUjQ3HbO+XLER1Frpp2wlY3rYGJgyh4z80lH5aLydqmWJJJzFFR8vScbYt27HGyD/C9m0AvzAIuTDpntj+EYSLUbYavxY4zG3EY5e+/uCSfX4FXnz2y1QP0nfvFMvMEQA9jaeQ/HRZjr2m6QTKmapAqsK7/KKHrNl/1H4zYfeXB9yELgI7Dv36GPmxTNSvIh0=
  - secure: WVr2S4IXxtrdbQNJFOyx1m71iVILKKpqJPAb8KUfVlZSHVK/2pKtk/IRAVRZxtY3V/Gq66PKZ59pjpyZiL3wa0qvaDjCyr/x5VwqzrVp/TOUGmPHvZgoZ24MRXoXBhw6fkAjswxzd/bu2jXQsfCCn6xHDUlzFGlqSBcnnykpp72OzoIcXZn8ubBSBfoM4jsxMnhyQAfmqdVAFzsKHArXDNt7DqHBD7fmL6WfVvPdqTnQsRozhflYrYTjRQFkHhw9k5k1nlhKlAXMsTWa8uRBjT1MiMwDWkRrj/YeZXwVI61HQL8UDwectfUz0lXLluNaKvP1diV0Uq1N9vAtiyj3wQtM3xp95QObsLdSisxfJIYBxnH157Qg4U1lpZE3nkhFe7qLz0OvjhDa9ISgYm6e272rzjtDN2ycjM5wjo1geYJxZQvbrzXo+YYDgvdy5SruQt4XGSH1V8lnQ0Qu07NNOwiJkKLOOXkgD/gTe6jwW2WKulw3khes98mHwJzCz2mo4yTDtul+5FawrzGIC6vvRP2P+4C9U4LJWBTbcQdKRLJX3HFr8W19nnEB+UQQJaRl5+cmhBzhUal22OZaKqqKOw3GptR1Pstdto2bqqP1+I49eYtcUoUDD0dE95sFjseeYpB9promER4Sqi46DV2gs7gDK38xeVGJkbQl/Cq5rIU=
