# config.toml file acts as a settings page for the site
baseurl = "https://benwhalley.co.uk/"
languageCode = "en-gb"
title = "Frontend Development - North West UK"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "blank"

[params]
    site_author = "Ben Whalley"
    author_email = "hey@benwhalley.co.uk"
    site_description = "The awesome blog of John Doe."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_title = "Ben Whalley - Portfolio"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[[menu.main]]
    name = "About"
    url = "/"
[[menu.main]]
    name = "Projects"
    url = "/projects"
[[menu.main]]
    name = "Blog"
    url = "/blog"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "digitalcraftsman"
gplus = ""
